-- This script was generated by the ERD tool in pgAdmin 4.
-- Veuillez signaler tout problème à https://redmine.postgresql.org/projects/pgadmin4/issues/new si vous trouvez des erreurs. Préciser dans le rapport les étapes pour le reproduire.
BEGIN;


CREATE TABLE IF NOT EXISTS public.utilisateur
(
    email           varchar(255),
    firstName       varchar(255),           
    lastName        varchar(255) ,           
    pwd             varchar(255),
    CONSTRAINT utilisateur_pkey PRIMARY KEY (email)
);
END;